// <auto-generated />
using Doctor.Microservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doctor.Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Doctor.Microservice.Entities.Doctor", b =>
                {
                    b.Property<int>("Doc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Contact_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Doc_Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Doc_Id = 1,
                            Age = 25,
                            Contact_No = "0761234567",
                            Email = "kasun@gmail.com",
                            Gender = "Male",
                            Name = "Dr.Dakshina Kasun",
                            Spec_Type = "Cardiologists"
                        },
                        new
                        {
                            Doc_Id = 2,
                            Age = 24,
                            Contact_No = "0711234567",
                            Email = "akash@gmail.com",
                            Gender = "Male",
                            Name = "Dr.Kaveen Akash",
                            Spec_Type = "Allergists"
                        },
                        new
                        {
                            Doc_Id = 3,
                            Age = 24,
                            Contact_No = "0771234567",
                            Email = "deshani@gmail.com",
                            Gender = "Female",
                            Name = "Dr.Deshani Dakshima",
                            Spec_Type = "Neurologists"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
