// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescription.Microservice.Data;

namespace Prescription.Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prescription.Microservice.Entities.Prescription", b =>
                {
                    b.Property<int>("Prs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doc_Id")
                        .HasColumnType("int");

                    b.Property<int>("Med_Id")
                        .HasColumnType("int");

                    b.Property<int>("Pat_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Prs_Id");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Prs_Id = 1,
                            Date = "05-06-2022",
                            Doc_Id = 1,
                            Med_Id = 2,
                            Pat_Id = 2,
                            Quantity = 18
                        },
                        new
                        {
                            Prs_Id = 2,
                            Date = "10-06-2022",
                            Doc_Id = 2,
                            Med_Id = 1,
                            Pat_Id = 3,
                            Quantity = 27
                        },
                        new
                        {
                            Prs_Id = 3,
                            Date = "07-06-2022",
                            Doc_Id = 3,
                            Med_Id = 3,
                            Pat_Id = 1,
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
