// <auto-generated />
using Medicine.Microservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medicine.Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220612085538_medseeddata")]
    partial class medseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medicine.Microservice.Entities.Medicine", b =>
                {
                    b.Property<int>("Med_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<int>("Curr_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Exp_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Init_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Med_Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Med_Id = 1,
                            Badge = 9854145,
                            Curr_Quantity = 2500,
                            Exp_Date = "01-12-2025",
                            Init_Quantity = 5000,
                            Name = "Amikacin"
                        },
                        new
                        {
                            Med_Id = 2,
                            Badge = 8424956,
                            Curr_Quantity = 1000,
                            Exp_Date = "01-12-2025",
                            Init_Quantity = 5000,
                            Name = "Crizotinib"
                        },
                        new
                        {
                            Med_Id = 3,
                            Badge = 4594252,
                            Curr_Quantity = 3280,
                            Exp_Date = "01-12-2025",
                            Init_Quantity = 5000,
                            Name = "Etoposid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
