// <auto-generated />
using Medicine.Microservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medicine.Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220612084832_medinitialmigration")]
    partial class medinitialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medicine.Microservice.Entities.Medicine", b =>
                {
                    b.Property<int>("Med_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<int>("Curr_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Exp_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Init_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Med_Id");

                    b.ToTable("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
